package Apresentacao;

public class frmAjuda extends javax.swing.JDialog
{

    public frmAjuda(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblTutorial = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        pnlTexto = new javax.swing.JPanel();
        lblTexto3 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        lblTexto4 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuda");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(960, 600));
        setSize(new java.awt.Dimension(960, 600));
        getContentPane().setLayout(null);

        lblTutorial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTutorial.setForeground(new java.awt.Color(51, 153, 0));
        lblTutorial.setText("Como Jogar?");
        getContentPane().add(lblTutorial);
        lblTutorial.setBounds(410, 40, 149, 32);

        btnVoltar.setBackground(new java.awt.Color(50, 50, 50));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(25, 255, 0));
        btnVoltar.setText("Voltar ao menu principal");
        btnVoltar.setFocusable(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(30, 470, 240, 50);

        pnlTexto.setBackground(new java.awt.Color(50, 50, 50));

        lblTexto3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTexto3.setForeground(new java.awt.Color(25, 255, 0));
        lblTexto3.setText("Ao iniciar, você tera 20 segundos para responer a questão, assim se repetindo até 10 perguntas, ao final da rodada seu resultado será exibido.");

        lblTexto2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(25, 255, 0));
        lblTexto2.setText("Toda vez que é iniciado, a ordem das perguntas acaba sendo aleatória, assim sendo mais difícil de decorá-las.");

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTexto1.setForeground(new java.awt.Color(25, 255, 0));
        lblTexto1.setText("Este é um jogo de perguntas e respostas normal com tema educativo, e com uma mecânica que faz com que toda partida seja diferente.");

        lblTexto4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTexto4.setForeground(new java.awt.Color(25, 255, 0));
        lblTexto4.setText("Sera que você sabe o bastante sobre educação ambiental? Esperamos que gostem do desafio e do quiz em sí, muito obrigado.");

        javax.swing.GroupLayout pnlTextoLayout = new javax.swing.GroupLayout(pnlTexto);
        pnlTexto.setLayout(pnlTextoLayout);
        pnlTextoLayout.setHorizontalGroup(
            pnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto3)
                    .addComponent(lblTexto2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTexto4, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlTextoLayout.setVerticalGroup(
            pnlTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblTexto2)
                .addGap(42, 42, 42)
                .addComponent(lblTexto3)
                .addGap(40, 40, 40)
                .addComponent(lblTexto4)
                .addGap(26, 26, 26))
        );

        getContentPane().add(pnlTexto);
        pnlTexto.setBounds(30, 150, 900, 240);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 960, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVoltarActionPerformed
    {//GEN-HEADEREND:event_btnVoltarActionPerformed
        dispose();
        frmMenuPrincipal frmM = new frmMenuPrincipal(null, true);
        frmM.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmAjuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmAjuda dialog = new frmAjuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JLabel lblTexto4;
    private javax.swing.JLabel lblTutorial;
    private javax.swing.JPanel pnlTexto;
    // End of variables declaration//GEN-END:variables
}
