package Apresentacao;

public class frmCreditos extends javax.swing.JDialog
{

    public frmCreditos(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblAgradecimento = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        lblNome3 = new javax.swing.JLabel();
        lblNome4 = new javax.swing.JLabel();
        lblNome5 = new javax.swing.JLabel();
        lblNome6 = new javax.swing.JLabel();
        lblNome7 = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creditos");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(801, 600));
        getContentPane().setLayout(null);

        lblAgradecimento.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblAgradecimento.setForeground(new java.awt.Color(0, 102, 0));
        lblAgradecimento.setText("Obrigado por Jogar!!");
        getContentPane().add(lblAgradecimento);
        lblAgradecimento.setBounds(230, 50, 360, 48);

        lblNome1.setBackground(new java.awt.Color(50, 50, 50));
        lblNome1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(204, 0, 0));
        lblNome1.setText("Gabriel Lima de Almeida                                                      N660GF2");
        getContentPane().add(lblNome1);
        lblNome1.setBounds(130, 210, 553, 25);

        lblNome2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(204, 0, 0));
        lblNome2.setText("Giovani Leonardo Brazão                                                     N5934B2");
        getContentPane().add(lblNome2);
        lblNome2.setBounds(130, 240, 555, 25);

        lblNome3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome3.setForeground(new java.awt.Color(204, 0, 0));
        lblNome3.setText("João Vitor Rodrigues Gauglitz                                             N5778H5");
        getContentPane().add(lblNome3);
        lblNome3.setBounds(130, 270, 557, 25);

        lblNome4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome4.setForeground(new java.awt.Color(204, 0, 0));
        lblNome4.setText("Letson Mendes de oliveira                                                    F331865");
        getContentPane().add(lblNome4);
        lblNome4.setBounds(130, 300, 560, 25);

        lblNome5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome5.setForeground(new java.awt.Color(204, 0, 0));
        lblNome5.setText("Michel Souza Paschoal dos Santos                                      F1305I8");
        getContentPane().add(lblNome5);
        lblNome5.setBounds(130, 330, 560, 25);

        lblNome6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome6.setForeground(new java.awt.Color(204, 0, 0));
        lblNome6.setText("Rafael Ribeiro de Araujo                                                       F205HC0");
        getContentPane().add(lblNome6);
        lblNome6.setBounds(130, 360, 560, 25);

        lblNome7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome7.setForeground(new java.awt.Color(204, 0, 0));
        lblNome7.setText("Vinícius Iudi Akagui Campos                                                N636EF0");
        getContentPane().add(lblNome7);
        lblNome7.setBounds(130, 390, 554, 25);

        lblSub.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSub.setForeground(new java.awt.Color(0, 102, 0));
        lblSub.setText("Membros do projeto APS");
        getContentPane().add(lblSub);
        lblSub.setBounds(270, 120, 269, 32);

        btnVoltar.setBackground(new java.awt.Color(50, 50, 50));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(25, 255, 0));
        btnVoltar.setText("Voltar para o menu principal");
        btnVoltar.setFocusable(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(40, 470, 270, 50);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVoltarActionPerformed
    {//GEN-HEADEREND:event_btnVoltarActionPerformed
        dispose();
        frmMenuPrincipal frmM = new frmMenuPrincipal(null, true);
        frmM.setVisible(true);  
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmCreditos dialog = new frmCreditos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblAgradecimento;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JLabel lblNome4;
    private javax.swing.JLabel lblNome5;
    private javax.swing.JLabel lblNome6;
    private javax.swing.JLabel lblNome7;
    private javax.swing.JLabel lblSub;
    // End of variables declaration//GEN-END:variables
}
